### ISSUE TITLE
Cannot read property 'length' of undefined bug

### ISSUE THREAD

**Issue by xtrinch** [xtrinch/react-touch-screen-keyboard#15]
When the value passed to the input is undefined:

Uncaught TypeError: Cannot read property 'length' of undefined
    at eval (KeyboardedInput.js:74)

**Comment by reganlawton** [comment]
is it line 74? That in `hideKeyboard` only place I see `length` used is in `handleFocus` line 59.

I could see a possible bug there. there's no logic to check that the `value` prop is present.

**Comment by reganlawton** [comment]
@xtrinch I did some testing and the issue is triggered when the `value` prop is empty or null. Adding `value: PropTypes.any.isRequired` wouldn't prevent the error and would only show two errors. Adding a defaultProps would cause the field to render but no value set making it pointless.

I came up with an extend fix based off the first which will make the prop required throwing a better error to show the developer the root cause. Then wrapped the `handleFocus` method with validation.

I've submitted a PR.

**Comment by xtrinch** [comment]
Well it wasn't a bad solution, and adding the fix I mentioned above, it renders this error message:

> warning.js?d66c:33 Warning: Failed prop type: The prop `value` is marked as required in `KeyboardedInput`, but its value is `undefined`.
>     in KeyboardedInput (created by MainComponent)
>     in MainComponent

Which is perfectly fine and acceptable and I would leave it at that. Released both PR's together in 3.0.0.

Thank you!

**Comment by reganlawton** [comment]
Haha I legit just pushing the typeof fix when i merged you bet me too it 👍
